### ISSUE TITLE
mean?

### ISSUE THREAD

**Issue by danieroux** [MastodonC/kixi.stats#25]
https://github.com/MastodonC/kixi.stats/blob/15772f411397546964c0a1216d0e5a7d68a3d9f6/src/kixi/stats/core.cljc#L96

That should be 

`(/ c s)`?

**Comment by henrygarner** [comment]
`c` and `s` are count and sum respectively. The arithmetic mean is the sum divided by the count, so `(/ s c)` is correct. The test [here](https://github.com/MastodonC/kixi.stats/blob/15772f411397546964c0a1216d0e5a7d68a3d9f6/test/kixi/stats/core_test.cljc#L322) verifies the implementation against a straightforward equivalent.

**Comment by danieroux** [comment]
It is not computing the sum divided by count:

```clojure
(kixi/mean [1 2 3]) => 1/2
```

**Comment by henrygarner** [comment]
The functions in `kixi.stats/core` are all reducing functions designed to work with `transduce` rather than be called directly. The [usage](https://github.com/MastodonC/kixi.stats#usage) section of the README should provide some helpful examples.

The arithmetic mean [test](https://github.com/MastodonC/kixi.stats/blob/master/test/kixi/stats/core_test.cljc#L325) should also reassure you that things are behaving as expected.

**Comment by danieroux** [comment]
Ah.

```clojure
(transduce identity kixi.stats.core/mean [1 2 3]) => 2.0
```

Thank you.
